### ISSUE TITLE
[FEATURE] Avoid triggering the tests when there is a change in markdown files

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#1451]

**Comment by miguelgfierro** [comment]
```
trigger:
  branches:
    include:
    - main
    - staging
  paths:
    exclude:
    - '*.md'
```
not working

**Comment by miguelgfierro** [comment]
with:
```
trigger:
  branches:
    include:
    - main
    - staging
  paths:
    exclude:
    - 'README.md'
```
and I modify a readme file that is not in the root, the builds are triggered: 
https://dev.azure.com/best-practices/recommenders/_build/results?buildId=48403&view=results
