### ISSUE TITLE
[FEATURE] Simplify AzureML test workflows

### ISSUE THREAD

**Issue by simonzhaoms** [microsoft/recommenders#1760]
### Description

After a quick look of the `azureml_*.yml` files under [.github/workflows](https://github.com/microsoft/recommenders/tree/staging/.github/workflows), I find the 4 `azureml_*.yml` files are almost the same except some parameters, such as `cpu`, `gpu`, etc.

```yaml
name: azureml-cpu-nightly

env:
  # Parameters
  EXP_NAME: nightly_cpu_tests

jobs:
  nightly-cpu-tests:
    # Shared Steps
    steps:
      - xxx
      - yyy
      - zzz
```

```yaml
name: azureml-gpu-nightly

env:
  # Parameters
  EXP_NAME: nightly_gpu_tests

jobs:
  nightly-gpu-tests:
    # Shared Steps
    steps:
      - xxx
      - yyy
      - zzz
```

To make them easier to read and maintain, [reusing workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) could be considered.  In other words, an extra reusable workflow file can be created to hold the common steps shared by the 4 `azureml_*.yml` files, and the 4 `azureml_*.yml` files only contains different parameters and a call to the reusable workflow.

```yaml
name: Reusable Workflow
on:
  workflow_call:
    inputs:
      # Parameters
      EXP_NAME:
        required: true
        type: string

jobs:
  test:
    # Shared Steps
    steps:
      - xxx
      - yyy
      - zzz
```

```yaml
name: azureml-cpu-nightly

jobs:
  nightly-cpu-tests:
    # Call reusable workflow
    uses: Reusable Workflow
    with:
      # Parameters
      EXP_NAME: nightly_cpu_tests
```

```yaml
name: azureml-gpu-nightly

jobs:
  nightly-gpu-tests:
    # Call reusable workflow
    uses: Reusable Workflow
    with:
      # Parameters
      EXP_NAME: nightly_gpu_tests
```
